version: '3.3'
services:
  php-apache-environment:
    container_name: php-apache8
    build: .
    volumes:
      - .:/var
      - ./src/public:/var/www/html
      - ./src:/var/www
    ports:
      - 8000:80
